# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "weather_tracker"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/trusty/20141212/trusty-server-cloudimg-i386-vagrant-disk1.box"

  # Underscore not permitted in hostname
  config.vm.hostname = "weather-tracker"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.provider "virtualbox" do |v|
    v.name = "weather_tracker"
  end

  config.vm.synced_folder "../../database/", "/home/vagrant/database"

  config.vm.provision "shell", path: "provision.sh"

  config.vm.network "private_network", ip: "192.168.67.87"
end
